### PR TITLE
Switch up the output of helpers

### PR DESCRIPTION
**Pull request by brianjhanson**
Since mixins don't work quite like functions, this switches things up a bit so they're actually output and can be turned off if you'd prefer.

### CODE REVIEW

**Comment by brianjhanson** [comment]
Sorry about the whitespace changes. My editorconfig had it's way with things. [Better Diff](https://github.com/onedesign/one-sass-toolkit/pull/2/files?w=1)

**Comment by cmalven** [comment]
@brianjhanson makes sense. Before we merge this in, can you bump the npm version on this PR so we can publish it as a new version after this work is merged:

```
npm version 0.2.0
```

**Comment by brianjhanson** [comment]
@cmalven done and done.

**Comment by cmalven** [comment]
Thanks @brianjhanson

**Pull request merged**
